#!/bin/bash
# Use this script to install in a user folder instead of a system folder,
# feel free to modify it
set -o xtrace
cd torcs-1.3.4-server/scr-patch
./do_patch.sh
cd ..
./configure --prefix=$(pwd)/../torcs-1.3.4-server-bin
make
make install
make datainstall
