import math

# All measures are in millimeters
class SkylakeCarConsts:
    RIM_DIAM_MM = 457.2
    TIRE_WIDTH_MM = 255
    TIRE_HEIGHT_MM = TIRE_WIDTH_MM * 0.4
    WHEEL_RADIUS_MM = RIM_DIAM_MM / 2.0 + TIRE_HEIGHT_MM
    TIRE_PERIMETER_MM = WHEEL_RADIUS_MM * 2.0 * math.pi
    TIRE_PERIMETER_M = TIRE_PERIMETER_MM / 1000.0
    WHEELS_DISTANCE_FRONT_M = 1.60
    WHEELS_DISTANCE_REAR_M = 1.68

    TORCS_SIMULATION_FREQUENCY = 50
    TORCS_SIMULATION_STEP = 1.0 / TORCS_SIMULATION_FREQUENCY

